### ISSUE TITLE
How do you close it?

### ISSUE THREAD

**Issue by youanan** [texadactyl/rpi_clock#1]
Hi! I very like this code, but, some times, I want display my desktop,How do you close it?

only: Go Back, Reboot, Shutdown,

**Comment by texadactyl** [comment]
Thank you for your interest.

Personally, I had no interest in showing the desktop. My device sits in my TV room and serves as a clock / weather display. I rarely interact with the device other than looking at it.

However, it would not be difficult to add an additional button to exit to the desktop if you want that option.  See the talk_to_operator procedure, around source line 165.  Note that adding a 4th button would probably cause you to adjust the sizes of objects (real estate issue).  I'd have readability concerns too.

Alternatively, you could replace one of the existing button functions.

**Comment by texadactyl** [comment]
By the way, I overkilled by installing Raspbian Stretch full.  I could have installed only the minimum command line Raspbian Stretch and just enough xorg to support the Tk GUI.  Anyways, you and I seem to have slightly different requirements in deployment.

**Comment by youanan** [comment]
@texadactyl  thank you! 
you are right!

**Comment by texadactyl** [comment]
@youanan - I added improved desktop support as one of the parameters in a configuration file (new). This new feature works fine on desktops.
