### ISSUE TITLE
Can't get it to work?

### ISSUE THREAD

**Issue by fatjuice** [texadactyl/rpi_clock#11]
I did how you described in the readme, but I cannot get it to work.

I should note that I am a complete newbie and this is very new to me, but I really like this idea for a project.

I get this:

$[2021-02-12 21:41:32,362]::CRITICAL::OOPS, initialization: Must not run in SSH session                                                     ^C
[1]+  Izlaz 86                ( cd $HOME/rpi_clock/bin; python3 rpi_clock.py rpi_clock.cfg 2>&1 > $HOME/rpi_clock.log )

also, cannot find autostart folder.

**Comment by texadactyl** [comment]
@fatjuice 

Pity you are having troubles.  What are you going to do with it?  Deploy a Raspberry Pi?  Run it on a PC?  Something else?

The symptom suggests that you were trying to run this project over an SSH connection from a client computer.  This will not work because the Python Tkintr toolkit does not support such a connection.  

Assuming that you are doing what I did, once you have set up a Raspberry Pi following the "Getting Started" section in README.md (docs/preparation_notes.txt), then the HDMI display, mouse, and keyboard are no longer needed.  Indeed, my Raspberry Pi runs with only a power connection just fine. 

Questions for you:
1. Did you follow the preparation notes precisely?
2. What was the set up and operations when this error occured?  What were you doing?
3. There is no "autostart" folder in this project.  Why did you ask that?

**Comment by fatjuice** [comment]
I deploying it on a raspberry pi 3b+ running rasbian.

1. Well, I have this 3,5' TFT screen and the LCD show was installed prior to me doing this, so I skipped the part of installing clone from github for the Lcdshow
2. Other than not been able to do the zenity part, I would reboot and touch the screen, but the rpi_clock wouldn't start.

3. I cannot do the following: 

* Get rid of zenity "Your Raspbian system has been upgraded …” messages 
which overlay the display by executing the following command:

	rm $HOME/.config/autostart/pi-conf-backup.desktop
	
	it tells me there is no such directory.

**Comment by texadactyl** [comment]
Maybe the $HOME/.config/autostart/pi-conf-backup.desktop file is not there.  If so, ignore the inability to remove it.

However, I am flying blind.  I do not know what you are seeing.  You need to include an image of the Pi after reboot completes.

"I would reboot and touch the screen, but the rpi_clock wouldn't start." is not descriptive enough.  
What happens?  What do you see?  The Pi desktop?  
Did you really do all the edits required in the preparation_notes.txt file?  E.g. $HOME/.profile

**Comment by fatjuice** [comment]
Hey,

I did a fresh install of Rasbian Stretch, just to be sure. I have studied the preparation_notes.txt file thoroughly to check if I missed a step.
So after the last step, in cloning from github and changing the parameters and inserting my API key, I reboot and I just see the dekstop of my rasbian OS.

I touch the screen as per the guide and no dialog box opens.

I added " (cd $HOME/rpi_clock/bin; python3 rpi_clock.py rpi_clock.cfg 2>&1 > $HOME/rpi_clock.log) &" in the $HOME/.profile at the end.

That would be it. Did all by the steps.


And I'd like to say, sorry for being a nuisance :)

**Comment by fatjuice** [comment]
I managed to run the rpi_clock.py from the little screen and been able to copy the log file.

Perhaps this could help?

`Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 317, in _cmd_ru$
    self.execute_current("Run")
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 295, in execute$
    self.execute_script(filename, args, working_directory, command_name)
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 266, in execute$
    get_shell().submit_magic_command(cd_cmd_line + exe_cmd_line)
  File "/usr/lib/python3/dist-packages/thonny/shell.py", line 98, in submit_mag$
    self.text.submit_command(cmd_line, ("magic",))
  File "/usr/lib/python3/dist-packages/thonny/shell.py", line 201, in submit_co$
    assert get_runner().is_waiting_toplevel_command()
AssertionError`

>

**Comment by texadactyl** [comment]
This:

```
Traceback (most recent call last): 
File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__ return self.func(*args) 
File "/usr/lib/python3/dist-packages/thonny/running.py", line 317, in _cmd_ru$ self.execute_current("Run") 
File "/usr/lib/python3/dist-packages/thonny/running.py", line 295, in execute$ self.execute_script(filename, args, working_directory, command_name) 
File "/usr/lib/python3/dist-packages/thonny/running.py", line 266, in execute$ get_shell().submit_magic_command(cd_cmd_line + exe_cmd_line) 
File "/usr/lib/python3/dist-packages/thonny/shell.py", line 98, in submit_mag$ self.text.submit_command(cmd_line, ("magic",)) 
File "/usr/lib/python3/dist-packages/thonny/shell.py", line 201, in submit_co$ assert get_runner().is_waiting_toplevel_command() AssertionError
```

tells me that:
* The Python program started and was in the process of trying to initialize tkinter.
* You have a Python version 3.5 on your Raspberry Pi.

My Raspberry Pi 2 and 4 are both running Python 3 version 3.8.5.  
When was the last time you updated the system software on your Raspberry Pi?

**Comment by texadactyl** [comment]
```
sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y autoclean
sudo apt-get -y autoremove
```

**Comment by texadactyl** [comment]
After you edited $HOME/.profile, did you reboot?

**Comment by fatjuice** [comment]
> After you edited $HOME/.profile, did you reboot?

Yes


> sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y autoclean
sudo apt-get -y autoremove

did that too.

This is my Rasbian version:

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian


I can only get python3.5.3?

I tried to do this [install from source](https://www.wyre-it.co.uk/blog/latestpython/).

the make command took forever, more than 8 hours and it still wasn't finished.

I'll just drop this, I'll need to get more acquainted with linux before I go install complicated stuff :/

**Comment by texadactyl** [comment]
If I were in your shoes, I would start by installing the latest Raspbian OS from 
https://www.raspberrypi.org/software/operating-systems/#raspberry-pi-os-32-bit

Stretch is out of date in terms of Python and many other OS components.

**Comment by texadactyl** [comment]
Closed due to lack of response.
