### ISSUE TITLE
Home directory for log file hard-coded to "/home/pi"

### ISSUE THREAD

**Issue by tehmessiah75** [texadactyl/rpi_clock#12]
**Describe the bug**
When i reboot the Pi after following your instruction i receive the following error

$ Traceback (most recent call last):
  File "/home/ben/rpi_clock/bin/rpi_clock.py", line 10, in <module>
    from tkinter import Button, Label, Tk
ModuleNotFoundError: No module named 'tkinter'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspian Bullseye Lite

**Comment by tehmessiah75** [comment]
I installed installed python3-tk which seemed to fix that issue however now it has another issue.

Output at boot:
```
Traceback (most recent call last):
  File "/home/ben/rpi_clock/bin/rpi_clock.py", line 15, in <module>
    parms = RpiClockParameters()
  File "/home/ben/rpi_clock/bin/rpi_clock_parameters.py", line 66, in __init__
    self.logging_init(log_file=home+"/rpi_clock.log", use_ts=True)
  File "/home/ben/rpi_clock/bin/rpi_clock_parameters.py", line 40, in logging_init
    fh = logging.FileHandler(log_file)
  File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/rpi_clock.log'
```

I'm guessing this is since the Pi imager now creates an actual user instead of default "pi"
Can you advise which files I need to update the strings to match my username?

**Comment by tehmessiah75** [comment]
after some investigation I tracked it down to:
`Line 65 of  /home/ben/rpi_clock/bin/rpi_clock_parameters.py home = "/home/pi"`
I changed it to: `home = "/home/ben"`
Now I get an error on reboot saying
```
[2022-12-02 14:38:22,928]::CRITICAL::OOPS, initialization: Must not run in SSH session

[1]+  Exit 86                 ( cd $HOME/rpi_clock/bin; python3 rpi_clock.py rpi_clock.cfg 2>&1 > $HOME/rpi_clock.log )
```

I'm running the OS with no GUI

**Comment by tehmessiah75** [comment]
I've upgrade the OS to XFCE and set it to auto boot to desktop and auto log me in however the rpi_clock isn't running.
What do I do now?

**Comment by tehmessiah75** [comment]
If I create a bash script in /usr/local/bin/clock.sh which has your script in it:

```
#!/bin/sh
# clock.sh
# 2 Dec 2022 Bash script to run tft clock and weather which is displayed on the 3.5" tft screen

(python3 /home/ben/rpi_clock/bin/rpi_clock.py /home/ben/rpi_clock/bin/rpi_clock.cfg 2>&1 > /home/ben/rpi_clock.log ) &
```
I can manually run it and it works.
If I run `(python3 /home/ben/rpi_clock/bin/rpi_clock.py /home/ben/rpi_clock/bin/rpi_clock.cfg 2>&1 > /home/ben/rpi_clock.log ) &` directly from terminal on the device it works.

If I do as your instructions say and add it to `~/.profile` it doesnt work.
If I add it to crontab to run the /usr/local/bin/clock.sh at login it doesnt work.

I dont know why or how this isnt working as designed.
Please help.

**Comment by texadactyl** [comment]
Just got back from vacation.  Will resolve this today.

**Comment by texadactyl** [comment]
@tehmessiah75 Thank you for your feedback.

Fixed to use actual home directory path.  Good catch.  I was careless!

Do NOT attempt to run this over SSH; I could not get the Tk infrastructure to work the last time I tried it.  I'll try it again as time permits.  I am guessing that you want to run with FLAG_WINDOWED = True for conventional display output over SSH as opposed to directly connect that quirky TFT hardware product directly connected.  True?

"I'm running the OS with no GUI".  Ok, I think (guessing) that you want to run a GUI over SSH?

It won't work with crontab as there is no display associated with crontab.

Appending .profile:  That works on a standard Raspbian system because the ```pi``` user is auto-logged in.  Thus, the .profile is executaed and the rpi_clock display is launched.  You can set up ```ben``` as the auto-login user instead.

Going to tryout Raspberry Pi OS with desktop on Debian bullseye (64-bit).  No point in useing "Lite" because Tk needs a desktop.

**Comment by tehmessiah75** [comment]
Sorry, I think I didn't explain it well enough.
I have a RPi 2B with a 3.5" touch screen hat (directly connected) which I setup headless as a Pi-Hole and [internet Speed-Test](https://github.com/arevindh/pihole-speedtest). All that was displayed on the screen was the terminal output from login (This is before I installed your RPi_Clock).

I thought it would be good to use the screen for something else and this RPi_Clock looked perfect.
When I first installed RPi_Clock I didn't realize I needed a Desktop Gui so I installed the XFCE desktop for it.
However after installing the clock it still doesn't work after reboot. I can manually run it and it works (sort of). I cannot get it to auto start at boot however. I also don't want it to run windowed.

> Appending .profile: That works on a standard Raspbian system because the pi user is auto-logged in. Thus, the .profile is executed and the rpi_clock display is launched. You can set up ben as the auto-login user instead.

This doesn't work. I did append it to the ~/.profile but it doesn't run after a reboot, the screen only shows the Desktop Gui.

I'd rather not reimage my SD card and have to rebuild my Pi-Hole.

Now every time I SSH to it to update the Pi-Hole or do other work to it I get the `OOPS: critical error` message. 
Is this an issue or is it just a warning that it wont work over SSH?

**Comment by tehmessiah75** [comment]
I also just noticed that your instructions say to download and image the SD card for the Pi with `* Download Raspbian Stretch Lite (latest) ==> a zip file.` (@line39 in rpi_clock/docs/preparation_notes.txt) except that you need the full desktop version not the lite version.

**Comment by texadactyl** [comment]
Open a separate issue for .profile if you wish

**Comment by texadactyl** [comment]
If you did not amend the lightdm configuration, then the autologin user is still ```pi```.  Do you want it to be ```ben```?
