### ISSUE TITLE
Two enhancement requests from @tehmessiah75

### ISSUE THREAD

**Issue by texadactyl** [texadactyl/rpi_clock#15]
Enhancement requests from @tehmessiah75:

1. "Configuration options to change the colour of (a) the background or (b) the text.  Just basic Red Green Blue Yellow or Black with a light background colour."

`>>>` Should be straight-forward using Tk.  The enhancements would effect the code and the config file.

2. "Change the startup location of the mouse cursor or somehow make the cursor hide after a 10 seconds (or some other predefined timeout). When mine loads the cursor is right in the middle of the screen over the temperature."

`>>>` I saw that too when I had a viable TFT screen to work with (It died!).  I thought that I defeated this anomaly but apparently not.  Note that I am having a lot of trouble ordering https://www.adafruit.com/product/2441 as a replacement.

**Comment by texadactyl** [comment]
@tehmessiah75

2023-02-07  v5.1
* Implement background and text color codes in the configuration file (issue #15).  See the sample config file.
* Attempt to fix reported cursor problem (issue #15): Turned cursor off before entering Tk mainloop.

**Comment by texadactyl** [comment]
@tehmessiah75
I'd really like you to test this proposed fix on your Adafruit screen before I close it.
Feedback?

**Comment by tehmessiah75** [comment]
@texadactyl 
I’m sorry. We’re in the process of moving and I’ll be offline for a few weeks.
I’ll test it for you once I’m back online.

**Comment by texadactyl** [comment]
@tehmessiah75 
No worries.  Moving can be a royal pain.

**Comment by tehmessiah75** [comment]
I just did a clean install and the background is now blue with white text.
I'll edit the config and see if I can change the color and give you an update.
I just noticed that the cursor isn't being displayed so that's a definite win :)

**Comment by tehmessiah75** [comment]
I can confirm the color adjustment is easy and works well.
In case you hadn't thought about, don't forget to update this into the instructions for everyone.

The default blue back ground with white text looks nice too.
Thank you very much, I greatly appreciate this addition. I believe this adds a nice touch to the app.
Keep up the good work

**Comment by texadactyl** [comment]
Color assignments added to preparation_notes.txt
