### ISSUE TITLE
not able to run

### ISSUE THREAD

**Issue by Hussamfhaily** [texadactyl/rpi_clock#2]
Hi, I got this message when I run the script:
[2019-02-11 18:36:37,248]::OOPS::CRITICAL::initialization: Configuration file path is required
[2019-02-11 18:36:37,248]::CRITICAL::initialization: Configuration file path is required

what am I supposed to do?
Many thanks

**Comment by texadactyl** [comment]
Did you follow the instructions as provided?  This message indicates that you haven't edited ```$HOME/.profile``` correctly.  See file ```docs/preparation_notes.txt``` lines 215-217.  

While you are at it, please re-read the entire set of preparation notes to make sure that you followed all steps completely.

Also, in file ```bin/rpi_clock.cfg```, make sure that you have edited 2 parameters:
* ```LOCATION_JSON``` - JSON file appropriate for your location
* ```WU_API_KEY``` - precise API key provided to you by Wundergound.com

**Comment by texadactyl** [comment]
@Hussamfhaily - Any progress?

**Comment by texadactyl** [comment]
I'll assume that you fixed a local issue since I have not heard back from you.

**Comment by Hussamfhaily** [comment]
@texadactyl 
Sorry for the late answer. I have stoped trying since the and when I have time I will check again. Thank you very much for your response.

**Comment by texadactyl** [comment]
Be sure to install rng-tools before trying again:
`sudo apt-get install rng-tools`
This is a different downstream issue but I might as well warn you.
There have been improvements added.  Suggest you reinstall code.

**Comment by LuxStatera** [comment]
I am also getting the same error. followed the preparation notes

**Comment by texadactyl** [comment]
@LuxStatera Please re-install and try again.  If you are unsuccessful after following the preparation_notes.txt procedure, then open a new issue and show the symptoms from standard output.  Also, in the event of failure, please attach as text files the following:
1. $HOME/rpi_clock/bin/rpi_clock.cfg
2. $HOME/.profile
3. Standard output from this command execution: ```ls -R $HOME```
