### ISSUE TITLE
How to display only clock?

### ISSUE THREAD

**Issue by MRDGH2821** [texadactyl/rpi_clock#9]
This seems to be a nice project and the closest one to solve my problem. 
I just want to know how to display only clock and nothing else, that too with larger font size?

**Comment by texadactyl** [comment]
You seem to want a different project.  I suggest that you download the ZIP, rename the project appropriately to your needs, and modify the source code.

**Comment by MRDGH2821** [comment]
> You seem to want a different project. I suggest that you download the ZIP and modify the source code.

Ok!
I got the code from somewhere fulfilling my purpose!
Still Thanks a lot!
The project is nice!
